version: '3.8' 

services:
  symfony:
    build:
      dockerfile: ./docker/symfony.Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - './app:/app'

  composer:
    build:
      dockerfile: ./docker/composer.Dockerfile
    # volumes:
    #   - './app:/app'

