version: '3.8' 

services:
  symfony:
    build:
      dockerfile: ./docker/symfony.Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - './app:/app'

  postgres:
    build:
      dockerfile: ./docker/postgres.Dockerfile
    ports:
      - '5432'
    volumes:
      # Contient une règle permettant au container Symfony de se connecter
      - './pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf'
      # TODO persist db 
    environment:
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: '!ChangeMe!'

  composer:
    build:
      dockerfile: ./docker/composer.Dockerfile
    volumes:
      - './app:/app'

  adminer:
    build:
      dockerfile: ./docker/adminer.Dockerfile
    ports:
      - '8080:8080'

